[build]
command = "pnpm build:docs"
publish = "apps/docs/dist"

[build.environment]
NODE_VERSION = "24"
PNPM_VERSION = "10"

[functions]
directory = "apps/docs/.netlify/functions-internal"
node_bundler = "esbuild"
