name: 'Feature Request'
description: 'Request a feature or enhancement'
labels: ['needs triage']
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for your contribution 😄!

        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'Please describe your request in one or two sentences.'
    validations:
      required: true
  - type: 'textarea'
    id: 'justification'
    attributes:
      label: 'What is the motivation / use case for changing the behavior?'
      description: 'Describe the motivation or the concrete use case.'
    validations:
      required: true
  - type: 'textarea'
    id: 'proposed-solution'
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen. Add any considered drawbacks'
    validations:
      required: true
  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: 'Additional context'
      description: 'Add any other context or screenshots about the feature request here.'
