name: 'Pull request'

on: [pull_request]

jobs:
  eslint:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm --filter "graneet-form" build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Test
        run: pnpm --filter "graneet-form" test
